In [1]:
import pandas as pd

In [27]:
NAME = '3b'
df = pd.read_csv('data-old/Poprawki/AOI_visit/3B.tsv', sep='\t')
df

,Recording,Participant,TOI,Interval,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit
0,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_com,8112,541.0,75.0,1583.0,15,3350.0,550.0
1,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0
2,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_plt,24302,2430.0,67.0,11499.0,10,28347.0,92.0
3,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_tab,6941,1388.0,83.0,6233.0,5,8174.0,400.0
4,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_txt,12691,3173.0,125.0,12124.0,4,37063.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_com,12907,2581.0,1458.0,3716.0,5,505.0,1458.0
196,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0
197,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_plt,34772,2898.0,133.0,17615.0,12,30.0,399.0
198,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_tab,4442,2221.0,250.0,4191.0,2,15739.0,4191.0
199,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_txt,66617,4164.0,34.0,20487.0,16,14825.0,292.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Recording                  200 non-null    object
 1   Participant                200 non-null    object
 2   TOI                        200 non-null    object
 3   Interval                   200 non-null    int64
 4   AOI                        200 non-null    object
 5   Total_duration_of_Visit    200 non-null    int64
 6   Average_duration_of_Visit  192 non-null    float64
 7   Minimum_duration_of_Visit  192 non-null    float64
 8   Maximum_duration_of_Visit  192 non-null    float64
 9   Number_of_Visits           200 non-null    int64
 10  Time_to_first_Visit        192 non-null    float64
 11  Duration_of_first_Visit    192 non-null    float64
dtypes: float64(5), int64(3), object(4)
memory usage: 18.9+ KB

In [29]:
# zmiana nazw kolumn
# usuniÄ™cie recordings
# unikalne indeksy - potem participants i recording, interwal do usuniÄ™cia

df['ID'] = df['Participant'].apply(lambda x: int(''.join(filter(str.isdigit, x))))
df.loc[df['ID'] == 28, 'ID'] = 29 # only 2B
df

,Recording,Participant,TOI,Interval,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_com,8112,541.0,75.0,1583.0,15,3350.0,550.0,46
1,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0,46
2,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_plt,24302,2430.0,67.0,11499.0,10,28347.0,92.0,46
3,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_tab,6941,1388.0,83.0,6233.0,5,8174.0,400.0,46
4,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_txt,12691,3173.0,125.0,12124.0,4,37063.0,300.0,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_com,12907,2581.0,1458.0,3716.0,5,505.0,1458.0,2
196,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0,2
197,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_plt,34772,2898.0,133.0,17615.0,12,30.0,399.0,2
198,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_tab,4442,2221.0,250.0,4191.0,2,15739.0,4191.0,2
199,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_txt,66617,4164.0,34.0,20487.0,16,14825.0,292.0,2

In [30]:
df = df[df['TOI'] != 'Entire Recording']
df

,Recording,Participant,TOI,Interval,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_com,8112,541.0,75.0,1583.0,15,3350.0,550.0,46
1,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0,46
2,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_plt,24302,2430.0,67.0,11499.0,10,28347.0,92.0,46
3,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_tab,6941,1388.0,83.0,6233.0,5,8174.0,400.0,46
4,Recording46,Participant46,zadanie_3_po_poprawce,1,3b_txt,12691,3173.0,125.0,12124.0,4,37063.0,300.0,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_com,12907,2581.0,1458.0,3716.0,5,505.0,1458.0,2
196,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0,2
197,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_plt,34772,2898.0,133.0,17615.0,12,30.0,399.0,2
198,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_tab,4442,2221.0,250.0,4191.0,2,15739.0,4191.0,2
199,Recording2,Participant2,zadanie_3_po_poprawce,1,3b_txt,66617,4164.0,34.0,20487.0,16,14825.0,292.0,2

In [31]:
df = df.drop(columns=['Recording', 'Participant', 'TOI', 'Interval'])
df

,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,3b_com,8112,541.0,75.0,1583.0,15,3350.0,550.0,46
1,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0,46
2,3b_plt,24302,2430.0,67.0,11499.0,10,28347.0,92.0,46
3,3b_tab,6941,1388.0,83.0,6233.0,5,8174.0,400.0,46
4,3b_txt,12691,3173.0,125.0,12124.0,4,37063.0,300.0,46
...,...,...,...,...,...,...,...,...,...
195,3b_com,12907,2581.0,1458.0,3716.0,5,505.0,1458.0,2
196,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0,2
197,3b_plt,34772,2898.0,133.0,17615.0,12,30.0,399.0,2
198,3b_tab,4442,2221.0,250.0,4191.0,2,15739.0,4191.0,2
199,3b_txt,66617,4164.0,34.0,20487.0,16,14825.0,292.0,2

In [32]:
df.rename(columns = {'Total_duration_of_Visit':'Total', 'Average_duration_of_Visit':'Avg', 'Minimum_duration_of_Visit':'Min', 'Maximum_duration_of_Visit':'Max', 'Number_of_Visits':'Num', 'Time_to_first_Visit':'TTV', 'Duration_of_first_Visit':'DTTV'}, inplace=True)
df

        AOI  Total     Avg     Min      Max  Num      TTV    DTTV  ID
0    3b_com   8112   541.0    75.0   1583.0   15   3350.0   550.0  46
1    3b_map  17490  2186.0    83.0   4066.0    8   7166.0   858.0  46
2    3b_plt  24302  2430.0    67.0  11499.0   10  28347.0    92.0  46
3    3b_tab   6941  1388.0    83.0   6233.0    5   8174.0   400.0  46
4    3b_txt  12691  3173.0   125.0  12124.0    4  37063.0   300.0  46
..      ...    ...     ...     ...      ...  ...      ...     ...  ..
195  3b_com  12907  2581.0  1458.0   3716.0    5    505.0  1458.0   2
196  3b_map   5275  2637.0   150.0   5125.0    2  19972.0  5125.0   2
197  3b_plt  34772  2898.0   133.0  17615.0   12     30.0   399.0   2
198  3b_tab   4442  2221.0   250.0   4191.0    2  15739.0  4191.0   2
199  3b_txt  66617  4164.0    34.0  20487.0   16  14825.0   292.0   2

[200 rows x 9 columns]

In [33]:
df_com = df[df['AOI'] == f'{NAME}_com']
df_map = df[df['AOI'] == f'{NAME}_map']
df_plt = df[df['AOI'] == f'{NAME}_plt']
df_tab = df[df['AOI'] == f'{NAME}_tab']
df_txt = df[df['AOI'] == f'{NAME}_txt']

In [34]:
df_map.set_index('ID', inplace=True)
df_com.set_index('ID', inplace=True)
df_plt.set_index('ID', inplace=True)
df_tab.set_index('ID', inplace=True)
df_txt.set_index('ID', inplace=True)

In [35]:
df_map

       AOI  Total      Avg      Min      Max  Num      TTV     DTTV
ID
46  3b_map  17490   2186.0     83.0   4066.0    8   7166.0    858.0
37  3b_map  29856   9952.0    483.0  27864.0    3   6696.0    483.0
23  3b_map   4133   2066.0    542.0   3591.0    2   9781.0    542.0
40  3b_map  10382   2596.0    600.0   4750.0    4   5743.0    600.0
19  3b_map   8149   1164.0    275.0   2433.0    7  16538.0   2433.0
31  3b_map  11275   2255.0    250.0   3942.0    5  12008.0    250.0
38  3b_map  15915   1447.0     92.0   4899.0   11  10422.0    150.0
35  3b_map  12799   2133.0    217.0  10408.0    6    365.0    708.0
42  3b_map  21342   2371.0    208.0  13783.0    9   6723.0    208.0
14  3b_map   9458   1576.0     75.0   6791.0    6   3834.0    292.0
3   3b_map  11891   1486.0    392.0   5566.0    8  13872.0    592.0
33  3b_map  22311   2231.0      4.0  16833.0   10      0.0      4.0
39  3b_map  10816  10816.0  10816.0  10816.0    1  48382.0  10816.0
16  3b_map  20014   1819.0    183.0   5791.0   11   7521.0    292.0
43  3b_map   4425    632.0    117.0   2433.0    7  28364.0    242.0
15  3b_map   4675   1558.0    217.0   4166.0    3    783.0    292.0
5   3b_map  18357   3060.0    125.0  14249.0    6   9783.0    125.0
27  3b_map  11779   2945.0     67.0  11187.0    4  54337.0  11187.0
12  3b_map  16648   1513.0     75.0   7533.0   11   9397.0    875.0
4   3b_map  16757   2394.0     92.0   7291.0    7   4311.0   1108.0
41  3b_map  18607   1861.0     75.0  11499.0   10  16697.0    975.0
7   3b_map  16774   2097.0    142.0   7033.0    8  46000.0   7033.0
30  3b_map    958    958.0    958.0    958.0    1  13433.0    958.0
24  3b_map   5483   1371.0    433.0   3883.0    4  28875.0    492.0
32  3b_map  31206   1836.0    183.0   9366.0   17   6472.0    717.0
20  3b_map   7883   1577.0    225.0   5259.0    5   5817.0    367.0
1   3b_map   1483    297.0    117.0    408.0    5   3463.0    308.0
25  3b_map   7499   1250.0    100.0   4066.0    6    426.0    100.0
21  3b_map  16124   1344.0    158.0   5408.0   12   4348.0    158.0
17  3b_map   8916   1783.0    217.0   3225.0    5   4551.0    217.0
11  3b_map  17118   3424.0    353.0  11224.0    5  16156.0    508.0
45  3b_map   6483   2161.0    783.0   4533.0    3   5439.0    783.0
34  3b_map   4958    451.0     67.0   1608.0   11  12091.0    367.0
29  3b_map  27502   3438.0    158.0  11957.0    8   8148.0   1191.0
13  3b_map  26164  13082.0   6800.0  19365.0    2   5132.0   6800.0
44  3b_map  16240   2030.0    133.0   5849.0    8  11386.0    392.0
18  3b_map   8567   1713.0    150.0   4741.0    5      0.0    198.0
22  3b_map  21286   3548.0    200.0  13274.0    6    361.0    200.0
26  3b_map  15482   1106.0    108.0   3441.0   14   4960.0    717.0
2   3b_map   5275   2637.0    150.0   5125.0    2  19972.0   5125.0

In [36]:
df_com = df_com.add_suffix(f'_{NAME}_com')
df_map = df_map.add_suffix(f'_{NAME}_map')
df_plt = df_plt.add_suffix(f'_{NAME}_plt')
df_tab = df_tab.add_suffix(f'_{NAME}_tab')
df_txt = df_txt.add_suffix(f'_{NAME}_txt')
df_map

,AOI_3b_map,Total_3b_map,Avg_3b_map,Min_3b_map,Max_3b_map,Num_3b_map,TTV_3b_map,DTTV_3b_map
ID,,,,,,,,
46,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0
37,3b_map,29856,9952.0,483.0,27864.0,3,6696.0,483.0
23,3b_map,4133,2066.0,542.0,3591.0,2,9781.0,542.0
40,3b_map,10382,2596.0,600.0,4750.0,4,5743.0,600.0
19,3b_map,8149,1164.0,275.0,2433.0,7,16538.0,2433.0
31,3b_map,11275,2255.0,250.0,3942.0,5,12008.0,250.0
38,3b_map,15915,1447.0,92.0,4899.0,11,10422.0,150.0
35,3b_map,12799,2133.0,217.0,10408.0,6,365.0,708.0
42,3b_map,21342,2371.0,208.0,13783.0,9,6723.0,208.0
14,3b_map,9458,1576.0,75.0,6791.0,6,3834.0,292.0
3,3b_map,11891,1486.0,392.0,5566.0,8,13872.0,592.0
33,3b_map,22311,2231.0,4.0,16833.0,10,0.0,4.0
39,3b_map,10816,10816.0,10816.0,10816.0,1,48382.0,10816.0
16,3b_map,20014,1819.0,183.0,5791.0,11,7521.0,292.0
43,3b_map,4425,632.0,117.0,2433.0,7,28364.0,242.0
15,3b_map,4675,1558.0,217.0,4166.0,3,783.0,292.0
5,3b_map,18357,3060.0,125.0,14249.0,6,9783.0,125.0
27,3b_map,11779,2945.0,67.0,11187.0,4,54337.0,11187.0
12,3b_map,16648,1513.0,75.0,7533.0,11,9397.0,875.0
4,3b_map,16757,2394.0,92.0,7291.0,7,4311.0,1108.0
41,3b_map,18607,1861.0,75.0,11499.0,10,16697.0,975.0
7,3b_map,16774,2097.0,142.0,7033.0,8,46000.0,7033.0
30,3b_map,958,958.0,958.0,958.0,1,13433.0,958.0
24,3b_map,5483,1371.0,433.0,3883.0,4,28875.0,492.0
32,3b_map,31206,1836.0,183.0,9366.0,17,6472.0,717.0
20,3b_map,7883,1577.0,225.0,5259.0,5,5817.0,367.0
1,3b_map,1483,297.0,117.0,408.0,5,3463.0,308.0
25,3b_map,7499,1250.0,100.0,4066.0,6,426.0,100.0
21,3b_map,16124,1344.0,158.0,5408.0,12,4348.0,158.0
17,3b_map,8916,1783.0,217.0,3225.0,5,4551.0,217.0
11,3b_map,17118,3424.0,353.0,11224.0,5,16156.0,508.0
45,3b_map,6483,2161.0,783.0,4533.0,3,5439.0,783.0
34,3b_map,4958,451.0,67.0,1608.0,11,12091.0,367.0
29,3b_map,27502,3438.0,158.0,11957.0,8,8148.0,1191.0
13,3b_map,26164,13082.0,6800.0,19365.0,2,5132.0,6800.0
44,3b_map,16240,2030.0,133.0,5849.0,8,11386.0,392.0
18,3b_map,8567,1713.0,150.0,4741.0,5,0.0,198.0
22,3b_map,21286,3548.0,200.0,13274.0,6,361.0,200.0
26,3b_map,15482,1106.0,108.0,3441.0,14,4960.0,717.0
2,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0

In [37]:
df = pd.merge(df_map, df_com, on='ID')
df = pd.merge(df, df_plt, on='ID')
df = pd.merge(df, df_tab, on='ID')
df = pd.merge(df, df_txt, on='ID')
df

,AOI_3b_map,Total_3b_map,Avg_3b_map,Min_3b_map,Max_3b_map,Num_3b_map,TTV_3b_map,DTTV_3b_map,AOI_3b_com,Total_3b_com,...,TTV_3b_tab,DTTV_3b_tab,AOI_3b_txt,Total_3b_txt,Avg_3b_txt,Min_3b_txt,Max_3b_txt,Num_3b_txt,TTV_3b_txt,DTTV_3b_txt
ID,,,,,,,,,,,,,,,,,,,,,
46,3b_map,17490,2186.0,83.0,4066.0,8,7166.0,858.0,3b_com,8112,...,8174.0,400.0,3b_txt,12691,3173.0,125.0,12124.0,4,37063.0,300.0
37,3b_map,29856,9952.0,483.0,27864.0,3,6696.0,483.0,3b_com,4458,...,15245.0,192.0,3b_txt,31389,15695.0,325.0,31064.0,2,19237.0,31064.0
23,3b_map,4133,2066.0,542.0,3591.0,2,9781.0,542.0,3b_com,6958,...,12956.0,11457.0,3b_txt,158,79.0,67.0,92.0,2,11581.0,67.0
40,3b_map,10382,2596.0,600.0,4750.0,4,5743.0,600.0,3b_com,2858,...,0.0,176.0,3b_txt,225,225.0,225.0,225.0,1,33949.0,225.0
19,3b_map,8149,1164.0,275.0,2433.0,7,16538.0,2433.0,3b_com,6999,...,23954.0,158.0,3b_txt,5300,5300.0,5300.0,5300.0,1,59060.0,5300.0
31,3b_map,11275,2255.0,250.0,3942.0,5,12008.0,250.0,3b_com,14807,...,10966.0,983.0,3b_txt,575,287.0,158.0,417.0,2,5475.0,158.0
38,3b_map,15915,1447.0,92.0,4899.0,11,10422.0,150.0,3b_com,6508,...,10647.0,158.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
35,3b_map,12799,2133.0,217.0,10408.0,6,365.0,708.0,3b_com,3592,...,39751.0,83.0,3b_txt,1533,767.0,675.0,858.0,2,7066.0,858.0
42,3b_map,21342,2371.0,208.0,13783.0,9,6723.0,208.0,3b_com,3266,...,22764.0,233.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
14,3b_map,9458,1576.0,75.0,6791.0,6,3834.0,292.0,3b_com,9749,...,10634.0,525.0,3b_txt,2783,2783.0,2783.0,2783.0,1,11250.0,2783.0
3,3b_map,11891,1486.0,392.0,5566.0,8,13872.0,592.0,3b_com,1937,...,13656.0,175.0,3b_txt,4108,2054.0,125.0,3983.0,2,42245.0,125.0
33,3b_map,22311,2231.0,4.0,16833.0,10,0.0,4.0,3b_com,6125,...,12528.0,2092.0,3b_txt,650,325.0,134.0,517.0,2,41751.0,134.0
39,3b_map,10816,10816.0,10816.0,10816.0,1,48382.0,10816.0,3b_com,2508,...,7160.0,125.0,3b_txt,27423,9141.0,183.0,17024.0,3,6918.0,183.0
16,3b_map,20014,1819.0,183.0,5791.0,11,7521.0,292.0,3b_com,5541,...,7321.0,142.0,3b_txt,17978,2568.0,67.0,16065.0,7,0.0,163.0
43,3b_map,4425,632.0,117.0,2433.0,7,28364.0,242.0,3b_com,0,...,15403.0,425.0,3b_txt,25267,2527.0,167.0,19482.0,10,0.0,231.0
15,3b_map,4675,1558.0,217.0,4166.0,3,783.0,292.0,3b_com,30372,...,14199.0,150.0,3b_txt,12282,2047.0,192.0,10082.0,6,12299.0,442.0
5,3b_map,18357,3060.0,125.0,14249.0,6,9783.0,125.0,3b_com,10607,...,16924.0,1066.0,3b_txt,175,175.0,175.0,175.0,1,61604.0,175.0
27,3b_map,11779,2945.0,67.0,11187.0,4,54337.0,11187.0,3b_com,11140,...,33647.0,942.0,3b_txt,492,246.0,133.0,358.0,2,65924.0,358.0
12,3b_map,16648,1513.0,75.0,7533.0,11,9397.0,875.0,3b_com,15540,...,0.0,377.0,3b_txt,275,137.0,92.0,183.0,2,43669.0,92.0
4,3b_map,16757,2394.0,92.0,7291.0,7,4311.0,1108.0,3b_com,8383,...,5486.0,433.0,3b_txt,658,658.0,658.0,658.0,1,99254.0,658.0
41,3b_map,18607,1861.0,75.0,11499.0,10,16697.0,975.0,3b_com,9674,...,27796.0,3333.0,3b_txt,9049,9049.0,9049.0,9049.0,1,18497.0,9049.0
7,3b_map,16774,2097.0,142.0,7033.0,8,46000.0,7033.0,3b_com,10741,...,28268.0,542.0,3b_txt,48387,6912.0,775.0,19282.0,7,9278.0,800.0
30,3b_map,958,958.0,958.0,958.0,1,13433.0,958.0,3b_com,841,...,12750.0,350.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
24,3b_map,5483,1371.0,433.0,3883.0,4,28875.0,492.0,3b_com,7107,...,11010.0,6008.0,3b_txt,21523,10762.0,10241.0,11282.0,2,18534.0,10241.0
32,3b_map,31206,1836.0,183.0,9366.0,17,6472.0,717.0,3b_com,16132,...,15038.0,300.0,3b_txt,29164,7291.0,208.0,26356.0,4,35453.0,1825.0
20,3b_map,7883,1577.0,225.0,5259.0,5,5817.0,367.0,3b_com,5649,...,6417.0,2108.0,3b_txt,13624,4541.0,133.0,9883.0,3,18766.0,133.0
1,3b_map,1483,297.0,117.0,408.0,5,3463.0,308.0,3b_com,2142,...,0.0,225.0,3b_txt,575,288.0,192.0,383.0,2,22036.0,192.0
25,3b_map,7499,1250.0,100.0,4066.0,6,426.0,100.0,3b_com,7199,...,11584.0,208.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
21,3b_map,16124,1344.0,158.0,5408.0,12,4348.0,158.0,3b_com,719,...,4165.0,125.0,3b_txt,5349,892.0,117.0,3966.0,6,35270.0,158.0
17,3b_map,8916,1783.0,217.0,3225.0,5,4551.0,217.0,3b_com,75,...,4818.0,592.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
11,3b_map,17118,3424.0,353.0,11224.0,5,16156.0,508.0,3b_com,3241,...,16715.0,1375.0,3b_txt,2858,714.0,200.0,1491.0,4,366.0,200.0
45,3b_map,6483,2161.0,783.0,4533.0,3,5439.0,783.0,3b_com,5191,...,3781.0,1033.0,3b_txt,658,658.0,658.0,658.0,1,34487.0,658.0
34,3b_map,4958,451.0,67.0,1608.0,11,12091.0,367.0,3b_com,4224,...,11158.0,233.0,3b_txt,5216,435.0,67.0,1750.0,12,1584.0,125.0
29,3b_map,27502,3438.0,158.0,11957.0,8,8148.0,1191.0,3b_com,7658,...,6324.0,1766.0,3b_txt,58787,8398.0,83.0,25873.0,7,9440.0,1808.0
13,3b_map,26164,13082.0,6800.0,19365.0,2,5132.0,6800.0,3b_com,4875,...,24722.0,4066.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
44,3b_map,16240,2030.0,133.0,5849.0,8,11386.0,392.0,3b_com,9533,...,11011.0,325.0,3b_txt,24290,6072.0,108.0,12799.0,4,10436.0,150.0
18,3b_map,8567,1713.0,150.0,4741.0,5,0.0,198.0,3b_com,9037,...,11847.0,150.0,3b_txt,0,NaN,NaN,NaN,0,NaN,NaN
22,3b_map,21286,3548.0,200.0,13274.0,6,361.0,200.0,3b_com,13232,...,25717.0,8083.0,3b_txt,342,171.0,100.0,242.0,2,50075.0,242.0
26,3b_map,15482,1106.0,108.0,3441.0,14,4960.0,717.0,3b_com,7257,...,5727.0,233.0,3b_txt,575,287.0,100.0,475.0,2,43490.0,100.0
2,3b_map,5275,2637.0,150.0,5125.0,2,19972.0,5125.0,3b_com,12907,...,15739.0,4191.0,3b_txt,66617,4164.0,34.0,20487.0,16,14825.0,292.0

In [38]:
df = df.drop(columns=[f'AOI_{NAME}_com', f'AOI_{NAME}_map', f'AOI_{NAME}_plt', f'AOI_{NAME}_tab', f'AOI_{NAME}_txt'])
df

,Total_3b_map,Avg_3b_map,Min_3b_map,Max_3b_map,Num_3b_map,TTV_3b_map,DTTV_3b_map,Total_3b_com,Avg_3b_com,Min_3b_com,...,Num_3b_tab,TTV_3b_tab,DTTV_3b_tab,Total_3b_txt,Avg_3b_txt,Min_3b_txt,Max_3b_txt,Num_3b_txt,TTV_3b_txt,DTTV_3b_txt
ID,,,,,,,,,,,,,,,,,,,,,
46,17490,2186.0,83.0,4066.0,8,7166.0,858.0,8112,541.0,75.0,...,5,8174.0,400.0,12691,3173.0,125.0,12124.0,4,37063.0,300.0
37,29856,9952.0,483.0,27864.0,3,6696.0,483.0,4458,743.0,158.0,...,2,15245.0,192.0,31389,15695.0,325.0,31064.0,2,19237.0,31064.0
23,4133,2066.0,542.0,3591.0,2,9781.0,542.0,6958,1739.0,125.0,...,1,12956.0,11457.0,158,79.0,67.0,92.0,2,11581.0,67.0
40,10382,2596.0,600.0,4750.0,4,5743.0,600.0,2858,260.0,83.0,...,2,0.0,176.0,225,225.0,225.0,225.0,1,33949.0,225.0
19,8149,1164.0,275.0,2433.0,7,16538.0,2433.0,6999,1400.0,725.0,...,8,23954.0,158.0,5300,5300.0,5300.0,5300.0,1,59060.0,5300.0
31,11275,2255.0,250.0,3942.0,5,12008.0,250.0,14807,2961.0,808.0,...,3,10966.0,983.0,575,287.0,158.0,417.0,2,5475.0,158.0
38,15915,1447.0,92.0,4899.0,11,10422.0,150.0,6508,651.0,75.0,...,11,10647.0,158.0,0,NaN,NaN,NaN,0,NaN,NaN
35,12799,2133.0,217.0,10408.0,6,365.0,708.0,3592,299.0,67.0,...,1,39751.0,83.0,1533,767.0,675.0,858.0,2,7066.0,858.0
42,21342,2371.0,208.0,13783.0,9,6723.0,208.0,3266,653.0,142.0,...,9,22764.0,233.0,0,NaN,NaN,NaN,0,NaN,NaN
14,9458,1576.0,75.0,6791.0,6,3834.0,292.0,9749,1083.0,167.0,...,8,10634.0,525.0,2783,2783.0,2783.0,2783.0,1,11250.0,2783.0
3,11891,1486.0,392.0,5566.0,8,13872.0,592.0,1937,387.0,133.0,...,9,13656.0,175.0,4108,2054.0,125.0,3983.0,2,42245.0,125.0
33,22311,2231.0,4.0,16833.0,10,0.0,4.0,6125,2042.0,408.0,...,7,12528.0,2092.0,650,325.0,134.0,517.0,2,41751.0,134.0
39,10816,10816.0,10816.0,10816.0,1,48382.0,10816.0,2508,627.0,150.0,...,1,7160.0,125.0,27423,9141.0,183.0,17024.0,3,6918.0,183.0
16,20014,1819.0,183.0,5791.0,11,7521.0,292.0,5541,426.0,75.0,...,5,7321.0,142.0,17978,2568.0,67.0,16065.0,7,0.0,163.0
43,4425,632.0,117.0,2433.0,7,28364.0,242.0,0,NaN,NaN,...,5,15403.0,425.0,25267,2527.0,167.0,19482.0,10,0.0,231.0
15,4675,1558.0,217.0,4166.0,3,783.0,292.0,30372,3797.0,2416.0,...,7,14199.0,150.0,12282,2047.0,192.0,10082.0,6,12299.0,442.0
5,18357,3060.0,125.0,14249.0,6,9783.0,125.0,10607,1326.0,83.0,...,4,16924.0,1066.0,175,175.0,175.0,175.0,1,61604.0,175.0
27,11779,2945.0,67.0,11187.0,4,54337.0,11187.0,11140,1393.0,125.0,...,14,33647.0,942.0,492,246.0,133.0,358.0,2,65924.0,358.0
12,16648,1513.0,75.0,7533.0,11,9397.0,875.0,15540,818.0,92.0,...,8,0.0,377.0,275,137.0,92.0,183.0,2,43669.0,92.0
4,16757,2394.0,92.0,7291.0,7,4311.0,1108.0,8383,699.0,108.0,...,11,5486.0,433.0,658,658.0,658.0,658.0,1,99254.0,658.0
41,18607,1861.0,75.0,11499.0,10,16697.0,975.0,9674,2419.0,508.0,...,12,27796.0,3333.0,9049,9049.0,9049.0,9049.0,1,18497.0,9049.0
7,16774,2097.0,142.0,7033.0,8,46000.0,7033.0,10741,1534.0,300.0,...,10,28268.0,542.0,48387,6912.0,775.0,19282.0,7,9278.0,800.0
30,958,958.0,958.0,958.0,1,13433.0,958.0,841,280.0,125.0,...,2,12750.0,350.0,0,NaN,NaN,NaN,0,NaN,NaN
24,5483,1371.0,433.0,3883.0,4,28875.0,492.0,7107,418.0,75.0,...,3,11010.0,6008.0,21523,10762.0,10241.0,11282.0,2,18534.0,10241.0
32,31206,1836.0,183.0,9366.0,17,6472.0,717.0,16132,2689.0,600.0,...,15,15038.0,300.0,29164,7291.0,208.0,26356.0,4,35453.0,1825.0
20,7883,1577.0,225.0,5259.0,5,5817.0,367.0,5649,565.0,67.0,...,5,6417.0,2108.0,13624,4541.0,133.0,9883.0,3,18766.0,133.0
1,1483,297.0,117.0,408.0,5,3463.0,308.0,2142,306.0,67.0,...,6,0.0,225.0,575,288.0,192.0,383.0,2,22036.0,192.0
25,7499,1250.0,100.0,4066.0,6,426.0,100.0,7199,900.0,117.0,...,2,11584.0,208.0,0,NaN,NaN,NaN,0,NaN,NaN
21,16124,1344.0,158.0,5408.0,12,4348.0,158.0,719,360.0,69.0,...,16,4165.0,125.0,5349,892.0,117.0,3966.0,6,35270.0,158.0
17,8916,1783.0,217.0,3225.0,5,4551.0,217.0,75,75.0,75.0,...,4,4818.0,592.0,0,NaN,NaN,NaN,0,NaN,NaN
11,17118,3424.0,353.0,11224.0,5,16156.0,508.0,3241,360.0,117.0,...,3,16715.0,1375.0,2858,714.0,200.0,1491.0,4,366.0,200.0
45,6483,2161.0,783.0,4533.0,3,5439.0,783.0,5191,1298.0,858.0,...,6,3781.0,1033.0,658,658.0,658.0,658.0,1,34487.0,658.0
34,4958,451.0,67.0,1608.0,11,12091.0,367.0,4224,264.0,67.0,...,9,11158.0,233.0,5216,435.0,67.0,1750.0,12,1584.0,125.0
29,27502,3438.0,158.0,11957.0,8,8148.0,1191.0,7658,1532.0,125.0,...,4,6324.0,1766.0,58787,8398.0,83.0,25873.0,7,9440.0,1808.0
13,26164,13082.0,6800.0,19365.0,2,5132.0,6800.0,4875,609.0,117.0,...,1,24722.0,4066.0,0,NaN,NaN,NaN,0,NaN,NaN
44,16240,2030.0,133.0,5849.0,8,11386.0,392.0,9533,867.0,100.0,...,8,11011.0,325.0,24290,6072.0,108.0,12799.0,4,10436.0,150.0
18,8567,1713.0,150.0,4741.0,5,0.0,198.0,9037,904.0,83.0,...,2,11847.0,150.0,0,NaN,NaN,NaN,0,NaN,NaN
22,21286,3548.0,200.0,13274.0,6,361.0,200.0,13232,2646.0,125.0,...,4,25717.0,8083.0,342,171.0,100.0,242.0,2,50075.0,242.0
26,15482,1106.0,108.0,3441.0,14,4960.0,717.0,7257,403.0,92.0,...,19,5727.0,233.0,575,287.0,100.0,475.0,2,43490.0,100.0
2,5275,2637.0,150.0,5125.0,2,19972.0,5125.0,12907,2581.0,1458.0,...,2,15739.0,4191.0,66617,4164.0,34.0,20487.0,16,14825.0,292.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40 entries, 46 to 2
Data columns (total 35 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Total_3b_map  40 non-null     int64
 1   Avg_3b_map    40 non-null     float64
 2   Min_3b_map    40 non-null     float64
 3   Max_3b_map    40 non-null     float64
 4   Num_3b_map    40 non-null     int64
 5   TTV_3b_map    40 non-null     float64
 6   DTTV_3b_map   40 non-null     float64
 7   Total_3b_com  40 non-null     int64
 8   Avg_3b_com    39 non-null     float64
 9   Min_3b_com    39 non-null     float64
 10  Max_3b_com    39 non-null     float64
 11  Num_3b_com    40 non-null     int64
 12  TTV_3b_com    39 non-null     float64
 13  DTTV_3b_com   39 non-null     float64
 14  Total_3b_plt  40 non-null     int64
 15  Avg_3b_plt    40 non-null     float64
 16  Min_3b_plt    40 non-null     float64
 17  Max_3b_plt    40 non-null     float64
 18  Num_3b_plt    40 non-null     int64
 19  TTV_3b_plt    40 non-null     float64
 20  DTTV_3b_plt   40 non-null     float64
 21  Total_3b_tab  40 non-null     int64
 22  Avg_3b_tab    40 non-null     float64
 23  Min_3b_tab    40 non-null     float64
 24  Max_3b_tab    40 non-null     float64
 25  Num_3b_tab    40 non-null     int64
 26  TTV_3b_tab    40 non-null     float64
 27  DTTV_3b_tab   40 non-null     float64
 28  Total_3b_txt  40 non-null     int64
 29  Avg_3b_txt    33 non-null     float64
 30  Min_3b_txt    33 non-null     float64
 31  Max_3b_txt    33 non-null     float64
 32  Num_3b_txt    40 non-null     int64
 33  TTV_3b_txt    33 non-null     float64
 34  DTTV_3b_txt   33 non-null     float64
dtypes: float64(25), int64(10)
memory usage: 11.2 KB

In [40]:
df.to_csv(f'data-new/metrics/AOI_visit/{NAME}.csv', index=True)

In [41]:
# flow do aggregate
NAME = '2b-aggregate'
df = pd.read_csv('data-old/Poprawki/AOI_visit/2b-aggregate.tsv', sep='\t')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Recording                  40 non-null     object
 1   Participant                40 non-null     object
 2   TOI                        40 non-null     object
 3   Interval                   40 non-null     int64
 4   AOI                        40 non-null     object
 5   Total_duration_of_Visit    40 non-null     int64
 6   Average_duration_of_Visit  40 non-null     int64
 7   Minimum_duration_of_Visit  40 non-null     int64
 8   Maximum_duration_of_Visit  40 non-null     int64
 9   Number_of_Visits           40 non-null     int64
 10  Time_to_first_Visit        40 non-null     int64
 11  Duration_of_first_Visit    40 non-null     int64
dtypes: int64(8), object(4)
memory usage: 3.9+ KB

In [42]:
df['ID'] = df['Participant'].apply(lambda x: int(''.join(filter(str.isdigit, x))))
df.loc[df['ID'] == 28, 'ID'] = 29 # only 2B
df

,Recording,Participant,TOI,Interval,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,Recording46,Participant46,zadanie_2_po_poprawce,1,2B,95430,10603,317,50912,9,10164,4722,46
1,Recording37,Participant37,zadanie_2_po_poprawce,1,2B,64795,7199,108,24798,9,210,117,37
2,Recording23,Participant23,zadanie_2_po_poprawce,1,2B,35951,5136,66,10791,7,122,66,23
3,Recording40,Participant40,zadanie_2_po_poprawce,1,2B,40205,5026,125,12541,8,49,158,40
4,Recording19,Participant19,zadanie_2_po_poprawce,1,2B,36455,7291,250,24798,5,91,250,19
5,Recording31,Participant31,zadanie_2_po_poprawce,1,2B,14825,7413,3425,11400,2,5582,3425,31
6,Recording38,Participant38,zadanie_2_po_poprawce,1,2B,18177,3029,75,8858,6,0,386,38
7,Recording35,Participant35,zadanie_2_po_poprawce,1,2B,9158,3053,83,4958,3,85,83,35
8,Recording42,Participant42,zadanie_2_po_poprawce,1,2B,25166,5033,23,12666,5,0,23,42
9,Recording14,Participant14,zadanie_2_po_poprawce,1,2B,84378,28126,108,83873,3,0,396,14
10,Recording3,Participant3,zadanie_2_po_poprawce,1,2B,12999,1625,92,5633,8,377,92,3
11,Recording33,Participant33,zadanie_2_po_poprawce,1,2B,73058,12176,39,40963,6,0,39,33
12,Recording39,Participant39,zadanie_2_po_poprawce,1,2B,50298,12574,1042,42805,4,0,1042,39
13,Recording16,Participant16,zadanie_2_po_poprawce,1,2B,45173,11293,154,44005,4,0,154,16
14,Recording43,Participant43,zadanie_2_po_poprawce,1,2B,60848,8693,925,18925,7,25,4141,43
15,Recording15,Participant15,zadanie_2_po_poprawce,1,2B,83001,20750,258,44896,4,0,541,15
16,Recording5,Participant5,zadanie_2_po_poprawce,1,2B,13586,2717,133,8716,5,189,133,5
17,Recording27,Participant27,zadanie_2_po_poprawce,1,2B,50888,7270,75,19090,7,792,3058,27
18,Recording12,Participant12,zadanie_2_po_poprawce,1,2B,58142,5814,225,19840,10,0,270,12
19,Recording4,Participant4,zadanie_2_po_poprawce,1,2B,30747,7687,308,15374,4,4456,308,4
20,Recording41,Participant41,zadanie_2_po_poprawce,1,2B,28393,7098,362,23590,4,0,362,41
21,Recording7,Participant7,zadanie_2_po_poprawce,1,2B,48012,9602,608,29930,5,4577,608,7
22,Recording29,Participant29,zadanie_2_po_poprawce,1,2B,57117,19039,92,56642,3,72,383,29
23,Recording30,Participant30,zadanie_2_po_poprawce,1,2B,20565,2571,92,9166,8,606,92,30
24,Recording24,Participant24,zadanie_2_po_poprawce,1,2B,12616,2103,92,5366,6,194,92,24
25,Recording32,Participant32,zadanie_2_po_poprawce,1,2B,79854,13309,292,38497,6,108,292,32
26,Recording20,Participant20,zadanie_2_po_poprawce,1,2B,43957,7326,252,25581,6,0,316,20
27,Recording1,Participant1,zadanie_2_po_poprawce,1,2B,51716,8619,142,42086,6,0,142,1
28,Recording25,Participant25,zadanie_2_po_poprawce,1,2B,89385,14897,208,38463,6,0,4800,25
29,Recording21,Participant21,zadanie_2_po_poprawce,1,2B,30324,6065,175,25123,5,0,792,21
30,Recording17,Participant17,zadanie_2_po_poprawce,1,2B,15208,2535,19,6800,6,0,19,17
31,Recording11,Participant11,zadanie_2_po_poprawce,1,2B,43590,10897,144,37572,4,0,144,11
32,Recording45,Participant45,zadanie_2_po_poprawce,1,2B,24964,3121,83,16457,8,65,83,45
33,Recording34,Participant34,zadanie_2_po_poprawce,1,2B,65211,4658,67,24948,14,362,592,34
34,Recording13,Participant13,zadanie_2_po_poprawce,1,2B,5739,1913,400,4916,3,0,423,13
35,Recording44,Participant44,zadanie_2_po_poprawce,1,2B,55120,9187,133,38238,6,0,133,44
36,Recording18,Participant18,zadanie_2_po_poprawce,1,2B,114353,19059,200,51438,6,87,358,18
37,Recording22,Participant22,zadanie_2_po_poprawce,1,2B,22832,3805,292,13566,6,150,292,22
38,Recording26,Participant26,zadanie_2_po_poprawce,1,2B,84602,6043,108,27614,14,2340,4133,26
39,Recording2,Participant2,zadanie_2_po_poprawce,1,2B,75666,15133,9,49888,5,3639,483,2

In [43]:
df = df[df['TOI'] != 'Entire Recording']
df

,Recording,Participant,TOI,Interval,AOI,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,Recording46,Participant46,zadanie_2_po_poprawce,1,2B,95430,10603,317,50912,9,10164,4722,46
1,Recording37,Participant37,zadanie_2_po_poprawce,1,2B,64795,7199,108,24798,9,210,117,37
2,Recording23,Participant23,zadanie_2_po_poprawce,1,2B,35951,5136,66,10791,7,122,66,23
3,Recording40,Participant40,zadanie_2_po_poprawce,1,2B,40205,5026,125,12541,8,49,158,40
4,Recording19,Participant19,zadanie_2_po_poprawce,1,2B,36455,7291,250,24798,5,91,250,19
5,Recording31,Participant31,zadanie_2_po_poprawce,1,2B,14825,7413,3425,11400,2,5582,3425,31
6,Recording38,Participant38,zadanie_2_po_poprawce,1,2B,18177,3029,75,8858,6,0,386,38
7,Recording35,Participant35,zadanie_2_po_poprawce,1,2B,9158,3053,83,4958,3,85,83,35
8,Recording42,Participant42,zadanie_2_po_poprawce,1,2B,25166,5033,23,12666,5,0,23,42
9,Recording14,Participant14,zadanie_2_po_poprawce,1,2B,84378,28126,108,83873,3,0,396,14
10,Recording3,Participant3,zadanie_2_po_poprawce,1,2B,12999,1625,92,5633,8,377,92,3
11,Recording33,Participant33,zadanie_2_po_poprawce,1,2B,73058,12176,39,40963,6,0,39,33
12,Recording39,Participant39,zadanie_2_po_poprawce,1,2B,50298,12574,1042,42805,4,0,1042,39
13,Recording16,Participant16,zadanie_2_po_poprawce,1,2B,45173,11293,154,44005,4,0,154,16
14,Recording43,Participant43,zadanie_2_po_poprawce,1,2B,60848,8693,925,18925,7,25,4141,43
15,Recording15,Participant15,zadanie_2_po_poprawce,1,2B,83001,20750,258,44896,4,0,541,15
16,Recording5,Participant5,zadanie_2_po_poprawce,1,2B,13586,2717,133,8716,5,189,133,5
17,Recording27,Participant27,zadanie_2_po_poprawce,1,2B,50888,7270,75,19090,7,792,3058,27
18,Recording12,Participant12,zadanie_2_po_poprawce,1,2B,58142,5814,225,19840,10,0,270,12
19,Recording4,Participant4,zadanie_2_po_poprawce,1,2B,30747,7687,308,15374,4,4456,308,4
20,Recording41,Participant41,zadanie_2_po_poprawce,1,2B,28393,7098,362,23590,4,0,362,41
21,Recording7,Participant7,zadanie_2_po_poprawce,1,2B,48012,9602,608,29930,5,4577,608,7
22,Recording29,Participant29,zadanie_2_po_poprawce,1,2B,57117,19039,92,56642,3,72,383,29
23,Recording30,Participant30,zadanie_2_po_poprawce,1,2B,20565,2571,92,9166,8,606,92,30
24,Recording24,Participant24,zadanie_2_po_poprawce,1,2B,12616,2103,92,5366,6,194,92,24
25,Recording32,Participant32,zadanie_2_po_poprawce,1,2B,79854,13309,292,38497,6,108,292,32
26,Recording20,Participant20,zadanie_2_po_poprawce,1,2B,43957,7326,252,25581,6,0,316,20
27,Recording1,Participant1,zadanie_2_po_poprawce,1,2B,51716,8619,142,42086,6,0,142,1
28,Recording25,Participant25,zadanie_2_po_poprawce,1,2B,89385,14897,208,38463,6,0,4800,25
29,Recording21,Participant21,zadanie_2_po_poprawce,1,2B,30324,6065,175,25123,5,0,792,21
30,Recording17,Participant17,zadanie_2_po_poprawce,1,2B,15208,2535,19,6800,6,0,19,17
31,Recording11,Participant11,zadanie_2_po_poprawce,1,2B,43590,10897,144,37572,4,0,144,11
32,Recording45,Participant45,zadanie_2_po_poprawce,1,2B,24964,3121,83,16457,8,65,83,45
33,Recording34,Participant34,zadanie_2_po_poprawce,1,2B,65211,4658,67,24948,14,362,592,34
34,Recording13,Participant13,zadanie_2_po_poprawce,1,2B,5739,1913,400,4916,3,0,423,13
35,Recording44,Participant44,zadanie_2_po_poprawce,1,2B,55120,9187,133,38238,6,0,133,44
36,Recording18,Participant18,zadanie_2_po_poprawce,1,2B,114353,19059,200,51438,6,87,358,18
37,Recording22,Participant22,zadanie_2_po_poprawce,1,2B,22832,3805,292,13566,6,150,292,22
38,Recording26,Participant26,zadanie_2_po_poprawce,1,2B,84602,6043,108,27614,14,2340,4133,26
39,Recording2,Participant2,zadanie_2_po_poprawce,1,2B,75666,15133,9,49888,5,3639,483,2

In [44]:
df = df.drop(columns=['Recording', 'Participant', 'TOI', 'AOI', 'Interval'])
df

,Total_duration_of_Visit,Average_duration_of_Visit,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,ID
0,95430,10603,317,50912,9,10164,4722,46
1,64795,7199,108,24798,9,210,117,37
2,35951,5136,66,10791,7,122,66,23
3,40205,5026,125,12541,8,49,158,40
4,36455,7291,250,24798,5,91,250,19
5,14825,7413,3425,11400,2,5582,3425,31
6,18177,3029,75,8858,6,0,386,38
7,9158,3053,83,4958,3,85,83,35
8,25166,5033,23,12666,5,0,23,42
9,84378,28126,108,83873,3,0,396,14
10,12999,1625,92,5633,8,377,92,3
11,73058,12176,39,40963,6,0,39,33
12,50298,12574,1042,42805,4,0,1042,39
13,45173,11293,154,44005,4,0,154,16
14,60848,8693,925,18925,7,25,4141,43
15,83001,20750,258,44896,4,0,541,15
16,13586,2717,133,8716,5,189,133,5
17,50888,7270,75,19090,7,792,3058,27
18,58142,5814,225,19840,10,0,270,12
19,30747,7687,308,15374,4,4456,308,4
20,28393,7098,362,23590,4,0,362,41
21,48012,9602,608,29930,5,4577,608,7
22,57117,19039,92,56642,3,72,383,29
23,20565,2571,92,9166,8,606,92,30
24,12616,2103,92,5366,6,194,92,24
25,79854,13309,292,38497,6,108,292,32
26,43957,7326,252,25581,6,0,316,20
27,51716,8619,142,42086,6,0,142,1
28,89385,14897,208,38463,6,0,4800,25
29,30324,6065,175,25123,5,0,792,21
30,15208,2535,19,6800,6,0,19,17
31,43590,10897,144,37572,4,0,144,11
32,24964,3121,83,16457,8,65,83,45
33,65211,4658,67,24948,14,362,592,34
34,5739,1913,400,4916,3,0,423,13
35,55120,9187,133,38238,6,0,133,44
36,114353,19059,200,51438,6,87,358,18
37,22832,3805,292,13566,6,150,292,22
38,84602,6043,108,27614,14,2340,4133,26
39,75666,15133,9,49888,5,3639,483,2

In [45]:
df.rename(columns = {'Total_duration_of_Visit':'Total', 'Average_duration_of_Visit':'Avg', 'Minimum_duration_of_Visit':'Min', 'Maximum_duration_of_Visit':'Max', 'Number_of_Visits':'Num', 'Time_to_first_Visit':'TTV', 'Duration_of_first_Visit':'DTTV'}, inplace=True)
df

     Total    Avg   Min    Max  Num    TTV  DTTV  ID
0    95430  10603   317  50912    9  10164  4722  46
1    64795   7199   108  24798    9    210   117  37
2    35951   5136    66  10791    7    122    66  23
3    40205   5026   125  12541    8     49   158  40
4    36455   7291   250  24798    5     91   250  19
5    14825   7413  3425  11400    2   5582  3425  31
6    18177   3029    75   8858    6      0   386  38
7     9158   3053    83   4958    3     85    83  35
8    25166   5033    23  12666    5      0    23  42
9    84378  28126   108  83873    3      0   396  14
10   12999   1625    92   5633    8    377    92   3
11   73058  12176    39  40963    6      0    39  33
12   50298  12574  1042  42805    4      0  1042  39
13   45173  11293   154  44005    4      0   154  16
14   60848   8693   925  18925    7     25  4141  43
15   83001  20750   258  44896    4      0   541  15
16   13586   2717   133   8716    5    189   133   5
17   50888   7270    75  19090    7    792  3058  27
18   58142   5814   225  19840   10      0   270  12
19   30747   7687   308  15374    4   4456   308   4
20   28393   7098   362  23590    4      0   362  41
21   48012   9602   608  29930    5   4577   608   7
22   57117  19039    92  56642    3     72   383  29
23   20565   2571    92   9166    8    606    92  30
24   12616   2103    92   5366    6    194    92  24
25   79854  13309   292  38497    6    108   292  32
26   43957   7326   252  25581    6      0   316  20
27   51716   8619   142  42086    6      0   142   1
28   89385  14897   208  38463    6      0  4800  25
29   30324   6065   175  25123    5      0   792  21
30   15208   2535    19   6800    6      0    19  17
31   43590  10897   144  37572    4      0   144  11
32   24964   3121    83  16457    8     65    83  45
33   65211   4658    67  24948   14    362   592  34
34    5739   1913   400   4916    3      0   423  13
35   55120   9187   133  38238    6      0   133  44
36  114353  19059   200  51438    6     87   358  18
37   22832   3805   292  13566    6    150   292  22
38   84602   6043   108  27614   14   2340  4133  26
39   75666  15133     9  49888    5   3639   483   2

In [46]:
df.set_index('ID', inplace=True)
df

     Total    Avg   Min    Max  Num    TTV  DTTV
ID
46   95430  10603   317  50912    9  10164  4722
37   64795   7199   108  24798    9    210   117
23   35951   5136    66  10791    7    122    66
40   40205   5026   125  12541    8     49   158
19   36455   7291   250  24798    5     91   250
31   14825   7413  3425  11400    2   5582  3425
38   18177   3029    75   8858    6      0   386
35    9158   3053    83   4958    3     85    83
42   25166   5033    23  12666    5      0    23
14   84378  28126   108  83873    3      0   396
3    12999   1625    92   5633    8    377    92
33   73058  12176    39  40963    6      0    39
39   50298  12574  1042  42805    4      0  1042
16   45173  11293   154  44005    4      0   154
43   60848   8693   925  18925    7     25  4141
15   83001  20750   258  44896    4      0   541
5    13586   2717   133   8716    5    189   133
27   50888   7270    75  19090    7    792  3058
12   58142   5814   225  19840   10      0   270
4    30747   7687   308  15374    4   4456   308
41   28393   7098   362  23590    4      0   362
7    48012   9602   608  29930    5   4577   608
29   57117  19039    92  56642    3     72   383
30   20565   2571    92   9166    8    606    92
24   12616   2103    92   5366    6    194    92
32   79854  13309   292  38497    6    108   292
20   43957   7326   252  25581    6      0   316
1    51716   8619   142  42086    6      0   142
25   89385  14897   208  38463    6      0  4800
21   30324   6065   175  25123    5      0   792
17   15208   2535    19   6800    6      0    19
11   43590  10897   144  37572    4      0   144
45   24964   3121    83  16457    8     65    83
34   65211   4658    67  24948   14    362   592
13    5739   1913   400   4916    3      0   423
44   55120   9187   133  38238    6      0   133
18  114353  19059   200  51438    6     87   358
22   22832   3805   292  13566    6    150   292
26   84602   6043   108  27614   14   2340  4133
2    75666  15133     9  49888    5   3639   483

In [47]:
df.to_csv(f'data-new/metrics/AOI_visit/{NAME}.csv', index=True)